
import React, { useState } from 'react';
import { ProcessDefinition } from '../types';
import { Rocket, Hammer, Copy } from 'lucide-react';
import { CatapulseLogo } from './Shared';

interface ModePegaProps {
    processDef: ProcessDefinition;
    pegaTab: 'blueprint' | 'manual';
    setPegaTab: (val: 'blueprint' | 'manual') => void;
}

export const ModePega: React.FC<ModePegaProps> = ({ processDef, pegaTab, setPegaTab }) => {
    return (
        <div className="max-w-4xl mx-auto py-12 px-6">
            <div className="flex justify-center mb-8 bg-gray-100 p-1 rounded-lg inline-flex mx-auto">
                 <button 
                    onClick={() => setPegaTab('blueprint')}
                    className={`px-6 py-2 rounded-md text-sm font-bold transition-all ${pegaTab === 'blueprint' ? 'bg-white text-sw-teal shadow-sm' : 'text-gray-500 hover:text-gray-900'}`}
                 >
                    Blueprint Generator
                 </button>
                 <button 
                    onClick={() => setPegaTab('manual')}
                    className={`px-6 py-2 rounded-md text-sm font-bold transition-all ${pegaTab === 'manual' ? 'bg-white text-sw-teal shadow-sm' : 'text-gray-500 hover:text-gray-900'}`}
                 >
                    Implementation Guide
                 </button>
            </div>
  
            {pegaTab === 'blueprint' ? (
                <div className="bg-white rounded-xl shadow-card border border-gray-200 p-8 text-center">
                    <div className="w-16 h-16 bg-blue-50 text-blue-600 rounded-full flex items-center justify-center mx-auto mb-6">
                        <Rocket size={32} />
                    </div>
                    <h2 className="text-2xl font-bold text-gray-800 mb-4">Pega GenAI Blueprint™ Prompt</h2>
                    <p className="text-gray-500 mb-8 max-w-lg mx-auto">
                        Copy the generated prompt below and paste it into Pega GenAI Blueprint to instantly scaffold this application structure.
                    </p>
                    
                    <div className="bg-gray-50 border border-gray-200 rounded-lg p-6 text-left font-mono text-sm text-gray-600 overflow-x-auto mb-6 whitespace-pre-wrap">
                        {`Create a Case Type named "${processDef.name}".
                        
  Description: ${processDef.description}
  
  Stages:
  ${processDef.stages.map(s => `- ${s.title}`).join('\n')}
  
  Data Model:
  ${processDef.stages.flatMap(s => s.sections).flatMap(sec => sec.elements).map(el => `- ${el.label} (${el.type})`).join('\n')}
                        `}
                    </div>
                    
                    <button className="bg-blue-600 text-white px-6 py-3 rounded-full font-bold hover:bg-blue-700 transition-colors flex items-center gap-2 mx-auto">
                        <Copy size={18} /> Copy to Clipboard
                    </button>
                </div>
            ) : (
                <div className="bg-white rounded-xl shadow-card border border-gray-200 p-8">
                    <h2 className="text-xl font-bold text-gray-800 mb-6 flex items-center gap-2">
                        <Hammer size={20} /> Developer Implementation Guide
                    </h2>
                    <div className="space-y-4">
                        {processDef.stages.map(stage => (
                            <div key={stage.id} className="border border-gray-100 rounded-lg overflow-hidden">
                                <div className="bg-gray-50 px-4 py-2 font-bold text-sm text-gray-600 border-b border-gray-100">
                                    Stage: {stage.title}
                                </div>
                                <div className="p-4">
                                    <ul className="space-y-2">
                                        {stage.sections.map(sec => (
                                            <li key={sec.id} className="text-sm">
                                                <span className="font-bold text-sw-teal">{sec.title}</span> maps to <code className="bg-gray-100 px-1 rounded text-xs">Rule-HTML-Section</code> with {sec.layout} template.
                                            </li>
                                        ))}
                                    </ul>
                                </div>
                            </div>
                        ))}
                    </div>
                    <div className="mt-8 pt-8 border-t border-gray-100 flex justify-between items-center text-gray-400">
                      <CatapulseLogo theme="light" scale={0.7} />
                      <p className="text-xs">Generated by Catapulse Process Engine</p>
                    </div>
                </div>
            )}
        </div>
    );
};
